// Generated by Selenium IDE
const { Builder, By, Key, until } = require('selenium-webdriver')
const assert = require('assert')

describe('CT_MundoSENAI', function() {
  this.timeout(30000)
  let driver
  let vars
  beforeEach(async function() {
    driver = await new Builder().forBrowser('chrome').build()
    vars = {}
  })
  afterEach(async function() {
    await driver.quit();
  })
  it('CT_MundoSENAI', async function() {
    // Test name: CT_MundoSENAI
    // Step # | name | target | value
    // 1 | open | / | 
    await driver.get("https://www.mundosenai.com.br/")
    // 2 | setWindowSize | 1347x731 | 
    await driver.manage().window().setRect({ width: 1347, height: 731 })
    // 3 | click | linkText=Cursos | 
    await driver.findElement(By.linkText("Cursos")).click()
    // 4 | click | linkText=Carreira | 
    await driver.findElement(By.linkText("Carreira")).click()
    // 5 | click | css=.nav | 
    await driver.findElement(By.css(".nav")).click()
    // 6 | click | linkText=Notícias | 
    await driver.findElement(By.linkText("Notícias")).click()
    // 7 | click | css=.search > .search-box-header | 
    await driver.findElement(By.css(".search > .search-box-header")).click()
    // 8 | click | css=form | 
    await driver.findElement(By.css("form")).click()
    // 9 | click | linkText=Fechar | 
    await driver.findElement(By.linkText("Fechar")).click()
  })
})
