// Generated by Selenium IDE
const { Builder, By, Key, until } = require('selenium-webdriver')
const assert = require('assert')

describe('CT_MundoSENAI2', function() {
  this.timeout(30000)
  let driver
  let vars
  beforeEach(async function() {
    driver = await new Builder().forBrowser('chrome').build()
    vars = {}
  })
  afterEach(async function() {
    await driver.quit();
  })
  async function waitForWindow(timeout = 2) {
    await driver.sleep(timeout)
    const handlesThen = vars["windowHandles"]
    const handlesNow = await driver.getAllWindowHandles()
    if (handlesNow.length > handlesThen.length) {
      return handlesNow.find(handle => (!handlesThen.includes(handle)))
    }
    throw new Error("New window did not appear before timeout")
  }
  it('CT_MundoSENAI2', async function() {
    // Test name: CT_MundoSENAI2
    // Step # | name | target | value
    // 1 | open | / | 
    await driver.get("https://www.mundosenai.com.br/")
    // 2 | setWindowSize | 1347x731 | 
    await driver.manage().window().setRect({ width: 1347, height: 731 })
    // 3 | click | css=.search > .search-box-header | 
    await driver.findElement(By.css(".search > .search-box-header")).click()
    // 4 | click | id=termo_busca | 
    await driver.findElement(By.id("termo_busca")).click()
    // 5 | type | id=termo_busca | administração
    await driver.findElement(By.id("termo_busca")).sendKeys("administração")
    // 6 | type | id=termo_busca | administração
    await driver.findElement(By.id("termo_busca")).sendKeys("administração")
    // 7 | sendKeys | id=termo_busca | ${KEY_ENTER}
    await driver.findElement(By.id("termo_busca")).sendKeys(Key.ENTER)
    // 8 | click | css=.search > .search-box-header | 
    await driver.findElement(By.css(".search > .search-box-header")).click()
    // 9 | click | id=termo_busca | 
    await driver.findElement(By.id("termo_busca")).click()
    // 10 | click | id=termo_busca | 
    await driver.findElement(By.id("termo_busca")).click()
    // 11 | click | id=termo_busca | 
    await driver.findElement(By.id("termo_busca")).click()
    // 12 | click | id=termo_busca | 
    await driver.findElement(By.id("termo_busca")).click()
    // 13 | type | id=termo_busca | segurança do trabalho
    await driver.findElement(By.id("termo_busca")).sendKeys("segurança do trabalho")
    // 14 | sendKeys | id=termo_busca | ${KEY_ENTER}
    await driver.findElement(By.id("termo_busca")).sendKeys(Key.ENTER)
    // 15 | click | linkText=Home | 
    await driver.findElement(By.linkText("Home")).click()
    // 16 | click | linkText=Acesse a Loja | 
    vars["windowHandles"] = await driver.getAllWindowHandles()
    // 17 | selectWindow | handle=${win3954} | 
    await driver.findElement(By.linkText("Acesse a Loja")).click()
    // 18 | select | css=.o-0 | label=Minas Gerais
    vars["win3954"] = await waitForWindow(2000)
    // 19 | click | css=.bg-action-primary > .vtex-button__label | 
    await driver.switchTo().window(vars["win3954"])
    {
      const dropdown = await driver.findElement(By.css(".o-0"))
      await dropdown.findElement(By.xpath("//option[. = 'Minas Gerais']")).click()
    }
    await driver.findElement(By.css(".bg-action-primary > .vtex-button__label")).click()
  })
})
