// Generated by Selenium IDE
const { Builder, By, Key, until } = require('selenium-webdriver')
const assert = require('assert')

describe('CT_consulta de frete', function() {
  this.timeout(30000)
  let driver
  let vars
  beforeEach(async function() {
    driver = await new Builder().forBrowser('chrome').build()
    vars = {}
  })
  afterEach(async function() {
    await driver.quit();
  })
  it('CT_consulta de frete', async function() {
    // Test name: CT_consulta de frete
    // Step # | name | target | value
    // 1 | open | https://leitura.com.br/index.php?route=checkout/cart | 
    await driver.get("https://leitura.com.br/index.php?route=checkout/cart")
    // 2 | setWindowSize | 1347x731 | 
    await driver.manage().window().setRect({ width: 1347, height: 731 })
    // 3 | click | css=.accordion-toggle > .fa | 
    await driver.findElement(By.css(".accordion-toggle > .fa")).click()
    // 4 | click | id=input-postcode | 
    await driver.findElement(By.id("input-postcode")).click()
    // 5 | type | id=input-postcode | 36774000
    await driver.findElement(By.id("input-postcode")).sendKeys("36774000")
    // 6 | click | id=button-quote | 
    await driver.findElement(By.id("button-quote")).click()
    // 7 | click | css=.radio:nth-child(6) input | 
    await driver.findElement(By.css(".radio:nth-child(6) input")).click()
    // 8 | click | id=button-shipping | 
    await driver.findElement(By.id("button-shipping")).click()
  })
})
