// Generated by Selenium IDE
const { Builder, By, Key, until } = require('selenium-webdriver')
const assert = require('assert')

describe('CT_TesteGeral3', function() {
  this.timeout(30000)
  let driver
  let vars
  beforeEach(async function() {
    driver = await new Builder().forBrowser('chrome').build()
    vars = {}
  })
  afterEach(async function() {
    await driver.quit();
  })
  it('CT_TesteGeral3', async function() {
    // Test name: CT_TesteGeral3
    // Step # | name | target | value
    // 1 | open | https://leitura.com.br/index.php?route=checkout/cart | 
    await driver.get("https://leitura.com.br/index.php?route=checkout/cart")
    // 2 | setWindowSize | 1335x718 | 
    await driver.manage().window().setRect({ width: 1335, height: 718 })
    // 3 | click | id=content | 
    await driver.findElement(By.id("content")).click()
    // 4 | click | linkText=Finalizar pedido | 
    await driver.findElement(By.linkText("Finalizar pedido")).click()
    // 5 | click | id=button-account | 
    await driver.findElement(By.id("button-account")).click()
    // 6 | click | id=input-payment-firstname | 
    await driver.findElement(By.id("input-payment-firstname")).click()
    // 7 | click | id=input-payment-company | 
    await driver.findElement(By.id("input-payment-company")).click()
    // 8 | click | id=input-payment-lastname | 
    await driver.findElement(By.id("input-payment-lastname")).click()
    // 9 | click | id=input-payment-postcode | 
    await driver.findElement(By.id("input-payment-postcode")).click()
    // 10 | click | id=input-payment-custom-field3 | 
    await driver.findElement(By.id("input-payment-custom-field3")).click()
    // 11 | click | id=input-payment-address-1 | 
    await driver.findElement(By.id("input-payment-address-1")).click()
    // 12 | click | id=input-payment-email | 
    await driver.findElement(By.id("input-payment-email")).click()
    // 13 | click | id=input-payment-address-2 | 
    await driver.findElement(By.id("input-payment-address-2")).click()
    // 14 | click | id=input-payment-custom-field4 | 
    await driver.findElement(By.id("input-payment-custom-field4")).click()
    // 15 | click | id=input-payment-country | 
    await driver.findElement(By.id("input-payment-country")).click()
    // 16 | click | id=input-payment-confirm-email | 
    await driver.findElement(By.id("input-payment-confirm-email")).click()
    // 17 | click | id=input-payment-custom-field1 | 
    await driver.findElement(By.id("input-payment-custom-field1")).click()
    // 18 | click | id=input-payment-telephone | 
    await driver.findElement(By.id("input-payment-telephone")).click()
    // 19 | click | id=input-payment-custom-field2 | 
    await driver.findElement(By.id("input-payment-custom-field2")).click()
    // 20 | click | id=input-payment-password | 
    await driver.findElement(By.id("input-payment-password")).click()
    // 21 | click | id=input-payment-zone | 
    await driver.findElement(By.id("input-payment-zone")).click()
    // 22 | click | id=input-payment-city | 
    await driver.findElement(By.id("input-payment-city")).click()
    // 23 | click | id=input-payment-password | 
    await driver.findElement(By.id("input-payment-password")).click()
    // 24 | click | id=input-payment-confirm | 
    await driver.findElement(By.id("input-payment-confirm")).click()
    // 25 | click | id=input-payment-city | 
    await driver.findElement(By.id("input-payment-city")).click()
    // 26 | click | css=#collapse-register .row | 
    await driver.findElement(By.css("#collapse-register .row")).click()
    // 27 | click | id=input-payment-captcha | 
    await driver.findElement(By.id("input-payment-captcha")).click()
    // 28 | click | id=input-email | 
    await driver.findElement(By.id("input-email")).click()
    // 29 | click | id=input-email | 
    await driver.findElement(By.id("input-email")).click()
    // 30 | click | id=input-password | 
    await driver.findElement(By.id("input-password")).click()
    // 31 | click | id=button-login | 
    await driver.findElement(By.id("button-login")).click()
    // 32 | click | css=.button-verification-code-login | 
    await driver.findElement(By.css(".button-verification-code-login")).click()
    // 33 | click | id=cancel-verification | 
    await driver.findElement(By.id("cancel-verification")).click()
  })
})
