// Generated by Selenium IDE
const { Builder, By, Key, until } = require('selenium-webdriver')
const assert = require('assert')

describe('CT_TesteGeral2', function() {
  this.timeout(30000)
  let driver
  let vars
  beforeEach(async function() {
    driver = await new Builder().forBrowser('chrome').build()
    vars = {}
  })
  afterEach(async function() {
    await driver.quit();
  })
  it('CT_TesteGeral2', async function() {
    // Test name: CT_TesteGeral2
    // Step # | name | target | value
    // 1 | open | https://leitura.com.br/index.php?route=checkout/cart | 
    await driver.get("https://leitura.com.br/index.php?route=checkout/cart")
    // 2 | setWindowSize | 1347x731 | 
    await driver.manage().window().setRect({ width: 1347, height: 731 })
    // 3 | click | css=.accordion-toggle > .fa | 
    await driver.findElement(By.css(".accordion-toggle > .fa")).click()
    // 4 | click | id=input-postcode | 
    await driver.findElement(By.id("input-postcode")).click()
    // 5 | click | id=button-quote | 
    await driver.findElement(By.id("button-quote")).click()
    // 6 | click | id=button-shipping | 
    await driver.findElement(By.id("button-shipping")).click()
    // 7 | click | linkText=Finalizar pedido | 
    await driver.findElement(By.linkText("Finalizar pedido")).click()
    // 8 | click | id=input-email | 
    await driver.findElement(By.id("input-email")).click()
    // 9 | click | id=input-password | 
    await driver.findElement(By.id("input-password")).click()
    // 10 | click | css=.panel-body > .row | 
    await driver.findElement(By.css(".panel-body > .row")).click()
    // 11 | click | id=button-login | 
    await driver.findElement(By.id("button-login")).click()
    // 12 | click | css=.button-verification-code-login | 
    await driver.findElement(By.css(".button-verification-code-login")).click()
    // 13 | mouseOver | css=.button-verification-code-login | 
    {
      const element = await driver.findElement(By.css(".button-verification-code-login"))
      await driver.actions({ bridge: true }).moveToElement(element).perform()
    }
    // 14 | mouseOut | css=.button-verification-code-login | 
    {
      const element = await driver.findElement(By.CSS_SELECTOR, "body")
      await driver.actions({ bridge: true }).moveToElement(element, 0, 0).perform()
    }
    // 15 | click | id=cancel-verification | 
    await driver.findElement(By.id("cancel-verification")).click()
    // 16 | click | id=button-account | 
    await driver.findElement(By.id("button-account")).click()
    // 17 | runScript | window.scrollTo(0,535) | 
    await driver.executeScript("window.scrollTo(0,535)")
  })
})
