// Generated by Selenium IDE
const { Builder, By, Key, until } = require('selenium-webdriver')
const assert = require('assert')

describe('CT_FiltroBusca', function() {
  this.timeout(30000)
  let driver
  let vars
  beforeEach(async function() {
    driver = await new Builder().forBrowser('chrome').build()
    vars = {}
  })
  afterEach(async function() {
    await driver.quit();
  })
  it('CT_FiltroBusca', async function() {
    // Test name: CT_FiltroBusca
    // Step # | name | target | value
    // 1 | open | /index.php?route=common/home | 
    await driver.get("https://leitura.com.br/index.php?route=common/home")
    // 2 | setWindowSize | 1347x731 | 
    await driver.manage().window().setRect({ width: 1347, height: 731 })
    // 3 | click | name=search | 
    await driver.findElement(By.name("search")).click()
    // 4 | type | name=search | cassandra clare
    await driver.findElement(By.name("search")).sendKeys("cassandra clare")
    // 5 | sendKeys | name=search | ${KEY_ENTER}
    await driver.findElement(By.name("search")).sendKeys(Key.ENTER)
    // 6 | click | name=search | 
    await driver.findElement(By.name("search")).click()
    // 7 | type | name=search | box instrumentos mortais
    await driver.findElement(By.name("search")).sendKeys("box instrumentos mortais")
    // 8 | click | css=.fa-search | 
    await driver.findElement(By.css(".fa-search")).click()
    // 9 | click | name=search | 
    await driver.findElement(By.name("search")).click()
    // 10 | mouseOver | css=.fa-search | 
    {
      const element = await driver.findElement(By.css(".fa-search"))
      await driver.actions({ bridge: true }).moveToElement(element).perform()
    }
    // 11 | type | name=search | as mulheres que corriam com os lobos
    await driver.findElement(By.name("search")).sendKeys("as mulheres que corriam com os lobos")
    // 12 | click | css=.fa-search | 
    await driver.findElement(By.css(".fa-search")).click()
    // 13 | mouseOut | css=.fa-search | 
    {
      const element = await driver.findElement(By.CSS_SELECTOR, "body")
      await driver.actions({ bridge: true }).moveToElement(element, 0, 0).perform()
    }
  })
})
